In [1]:
from IPython.display import display
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import mglearn
# 이 책에서의 기본 설정

In [3]:
# 분꽃 종류 분류하기
from sklearn.datasets import load_iris
iris_dataset= load_iris()

In [4]:
print("iris_dataset의 키 : \n", iris_dataset.keys())

iris_dataset의 키 : 
 dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [5]:
print(iris_dataset['DESCR'][:193] + "\n...")  # 데이터 셋에 대한 간략한 설명

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre
...


In [6]:
print("타깃의 이름 : ", iris_dataset['target_names']) # 우리가 예측하려는 품종의 이름 

타깃의 이름 :  ['setosa' 'versicolor' 'virginica']


In [7]:
print("특성의 이름 : \n", iris_dataset['feature_names'])

특성의 이름 : 
 ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [8]:
print("data의 타입:", type(iris_dataset['data']))
# 실제 데이터는 target과 data 필드에 들어있다.
# data는 꽃잎의 길이와 폭, 꽃받침의 길이와 폭을 수치값으로 가지는 numpy배열.

data의 타입: <class 'numpy.ndarray'>


In [9]:
print("data의 크기: ", iris_dataset['data'].shape)
# data 배열의 행은 개개의 꽃이 되며 열은 각 꽃에서 구한 네개의 측정치

data의 크기:  (150, 4)


In [10]:
print("data의 처음 닫섯 행:\n", iris_dataset['data'][:5])

data의 처음 닫섯 행:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [11]:
print("target의 타입:", type(iris_dataset['target']))

target의 타입: <class 'numpy.ndarray'>


In [13]:
print("target의 크기: ", iris_dataset['target'].shape)
# 타겟은 각 원소가 붓꽃 하나에 해당하는 1차원 배열

target의 크기:  (150,)


In [14]:
print("타깃:\n", iris_dataset['target'])
# 붓꽃의 종류는 0(setosa), 1(versicolor), 2(virginica)로 3종류이다.

타깃:
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [15]:
# data중 75%를 훈련용, 25%를 테스트 용으로 분리
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_dataset['data'], iris_dataset['target'], random_state = 0)
# train_test_split으로 데이터를 나누기 전 random_state로 데이터를 섞는다.
# 이 함수를 여러번 실행해도 같은 결과가 나오도록 유사 난수 생성기에 난수 초깃값을 random_state로 전달함.

In [16]:
print("X_train 크기 :", X_train.shape)
print("y_train 크기 :", y_train.shape)

X_train 크기 : (112, 4)
y_train 크기 : (112,)


In [17]:
print("X_test 크기: ", X_test.shape)
print("y_test 크기:", y_test.shape)

X_test 크기:  (38, 4)
y_test 크기: (38,)


In [ ]:
# X_train 데이터를 사용해서 데이터 프레임을 만듭니다
# 열의 이름은 iris_dataset.feature_names에 있는 문자열을 사용합니다.
iris_dataframe = pd.DataFrame(X_train, columns=iris_dataset.feature_names)